name: Framboos CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-image:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build client
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push -a ghcr.io/ionaru/framboos-2025-frontend
