name: Framboos CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build client
      - run: docker save -o client-image.tar ghcr.io/ionaru/framboos-2025-frontend:latest
      - uses: actions/upload-artifact@v4
        with:
          name: client-image
          path: client-image.tar
          retention-days: 1

  push-image:
    name: Push image
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: client-image
      - run: docker load -i client-image.tar
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push -a ghcr.io/ionaru/framboos-2025-frontend/client
